const diabeticDesserts = [
    {
      name: "วุ้นมะพร้าวอ่อน",
      image: "https://example.com/coconut_jelly.jpg",
      benefits: "แคลอรี่ต่ำและไม่มีน้ำตาลเพิ่ม",
      location: "123 ถนนสุขุมวิท, กรุงเทพฯ",
      calories: 50,
      category: "ของหวาน",
      ingredients: ["วุ้น", "มะพร้าวอ่อน", "หญ้าหวาน"],
      preparation: "ต้มวุ้นกับหญ้าหวานจนละลาย เทใส่พิมพ์และเติมมะพร้าวอ่อน",
      precautions: "ควรใช้หญ้าหวานแทนน้ำตาล",
      popularity: 4.5,
    },
    {
      name: "สลัดผลไม้รวม",
      image: "https://example.com/fruit_salad.jpg",
      benefits: "มีวิตามินสูงและไฟเบอร์",
      location: "456 ถนนรัชดาภิเษก, กรุงเทพฯ",
      calories: 80,
      category: "ของหวาน",
      ingredients: ["แอปเปิ้ลเขียว", "ฝรั่ง", "สตรอว์เบอร์รี่", "โยเกิร์ตไร้น้ำตาล"],
      preparation: "หั่นผลไม้เป็นชิ้นเล็ก ๆ ราดด้วยโยเกิร์ตไร้น้ำตาล",
      precautions: "หลีกเลี่ยงผลไม้ที่มีน้ำตาลสูง เช่น ทุเรียน, ลำไย",
      popularity: 4.2,
    },
    {
      name: "ถั่วแดงต้มหญ้าหวาน",
      image: "https://example.com/red_bean_dessert.jpg",
      benefits: "มีโปรตีนและไฟเบอร์สูง",
      location: "789 ถนนพระราม 4, กรุงเทพฯ",
      calories: 100,
      category: "ของหวาน",
      ingredients: ["ถั่วแดง", "หญ้าหวาน", "เกลือ"],
      preparation: "ต้มถั่วแดงจนนุ่ม เติมหญ้าหวานและเกลือเล็กน้อย",
      precautions: "ควรใช้หญ้าหวานแทนน้ำตาล",
      popularity: 4.0,
    },
    {
      name: "กล้วยน้ำว้าต้มอบเชย",
      image: "https://example.com/banana_cinnamon.jpg",
      benefits: "มีโพแทสเซียมและช่วยควบคุมน้ำตาลในเลือด",
      location: "321 ถนนสาทร, กรุงเทพฯ",
      calories: 90,
      category: "ของหวาน",
      ingredients: ["กล้วยน้ำว้า", "อบเชย", "หญ้าหวาน"],
      preparation: "ต้มกล้วยน้ำว้ากับอบเชยและหญ้าหวานจนนุ่ม",
      precautions: "ควรใช้หญ้าหวานแทนน้ำตาล",
      popularity: 4.1,
    },
    {
      name: "ชาเขียวเย็นหญ้าหวาน",
      image: "https://example.com/green_tea.jpg",
      benefits: "ช่วยเพิ่มความสดชื่นและไม่มีน้ำตาล",
      location: "654 ถนนสีลม, กรุงเทพฯ",
      calories: 20,
      category: "ของหวาน",
      ingredients: ["ชาเขียว", "หญ้าหวาน", "น้ำแข็ง"],
      preparation: "ชงชาเขียวกับหญ้าหวาน เติมน้ำแข็ง",
      precautions: "ควรใช้หญ้าหวานแทนน้ำตาล",
      popularity: 4.3,
    },
  ];