const savoryFoods = [ // อาหารคาว
    {
        name: "ข้าวกล้องผัดผักรวม",
        image: "https://example.com/brown_rice_stir_fry.jpg",
        benefits: "มีไฟเบอร์สูง ช่วยควบคุมระดับน้ำตาลในเลือด",
        location: "123 ถนนสุขุมวิท, กรุงเทพฯ",
        calories: 300,
        category: "อาหารคาว",
        ingredients: ["ข้าวกล้อง", "ผักรวม", "น้ำมันมะกอก", "กระเทียม"],
        preparation: "ผัดข้าวกล้องกับผักรวมในน้ำมันมะกอก ใส่กระเทียมสำหรับรสชาติ",
        precautions: "ควรใช้ปริมาณน้ำมันน้อย",
        popularity: 4.5,
    },
    {
        name: "แกงจืดเต้าหู้ไข่",
        image: "https://example.com/tofu_soup.jpg",
        benefits: "มีโปรตีนสูง ไขมันต่ำ",
        location: "456 ถนนรัชดาภิเษก, กรุงเทพฯ",
        calories: 180,
        category: "อาหารคาว",
        ingredients: ["เต้าหู้ไข่", "ผักกวางตุ้ง", "น้ำซุป", "กระเทียม"],
        preparation: "ต้มน้ำซุปให้เดือด ใส่เต้าหู้ไข่และผักกวางตุ้ง ต้มจนสุก",
        precautions: "ควรระวังปริมาณเกลือในน้ำซุป",
        popularity: 4.0,
    },
    {
        name: "สลัดปลาทูน่า",
        image: "https://example.com/tuna_salad.jpg",
        benefits: "มีโปรตีนสูงและไขมันดี",
        location: "789 ถนนพระราม 4, กรุงเทพฯ",
        calories: 250,
        category: "อาหารคาว",
        ingredients: ["ปลาทูน่า", "ผักสลัด", "มะเขือเทศ", "น้ำสลัดไขมันต่ำ"],
        preparation: "ผสมปลาทูน่ากับผักสลัดและมะเขือเทศ ราดน้ำสลัดไขมันต่ำ",
        precautions: "ควรเลือกน้ำสลัดที่ไม่มีน้ำตาลเพิ่ม",
        popularity: 4.3,
    },
    {
        name: "ผัดผักบุ้งไฟแดง",
        image: "https://example.com/stir_fry_morning_glory.jpg",
        benefits: "มีวิตามินเอสูง ช่วยบำรุงสายตา",
        location: "321 ถนนสีลม, กรุงเทพฯ",
        calories: 150,
        category: "อาหารคาว",
        ingredients: ["ผักบุ้ง", "พริกแดง", "กระเทียม", "น้ำมันมะกอก"],
        preparation: "ผัดผักบุ้งกับกระเทียมและพริกแดงในน้ำมันมะกอก",
        precautions: "ควรใช้ปริมาณน้ำมันน้อย",
        popularity: 4.2,
    },
    {
        name: "ต้มยำกุ้งน้ำใส",
        image: "https://example.com/tom_yum_shrimp.jpg",
        benefits: "มีโปรตีนจากกุ้งและรสชาติเผ็ดร้อนช่วยกระตุ้นระบบเผาผลาญ",
        location: "654 ถนนเพชรบุรี, กรุงเทพฯ",
        calories: 200,
        category: "อาหารคาว",
        ingredients: ["กุ้ง", "เห็ด", "มะนาว", "พริก", "ใบมะกรูด"],
        preparation: "ต้มน้ำซุปให้เดือด ใส่กุ้งและเห็ด ปรุงรสด้วยมะนาวและพริก",
        precautions: "ควรระวังปริมาณเกลือในน้ำซุป",
        popularity: 4.6,
    },
    {
        name: "ผัดบวบเห็ดหอม",
        image: "https://example.com/stir_fry_zucchini_mushroom.jpg",
        benefits: "มีไฟเบอร์สูงและแคลอรี่ต่ำ",
        location: "987 ถนนลาดพร้าว, กรุงเทพฯ",
        calories: 120,
        category: "อาหารคาว",
        ingredients: ["บวบ", "เห็ดหอม", "กระเทียม", "น้ำมันมะกอก"],
        preparation: "ผัดบวบและเห็ดหอมกับกระเทียมในน้ำมันมะกอก",
        precautions: "ควรใช้ปริมาณน้ำมันน้อย",
        popularity: 4.1,
    },
    {
        name: "แกงเลียงผักรวม",
        image: "https://example.com/vegetable_soup.jpg",
        benefits: "มีวิตามินและแร่ธาตุสูง",
        location: "111 ถนนราชดำริ, กรุงเทพฯ",
        calories: 180,
        category: "อาหารคาว",
        ingredients: ["ผักรวม", "กะทิ", "พริกไทย", "ใบแมงลัก"],
        preparation: "ต้มผักรวมกับกะทิ ปรุงรสด้วยพริกไทยและใบแมงลัก",
        precautions: "ควรใช้กะทิในปริมาณที่เหมาะสม",
        popularity: 4.0,
    },
    {
        name: "ยำวุ้นเส้น",
        image: "https://example.com/glass_noodle_salad.jpg",
        benefits: "มีแคลอรี่ต่ำและไฟเบอร์สูง",
        location: "222 ถนนสาทร, กรุงเทพฯ",
        calories: 160,
        category: "อาหารคาว",
        ingredients: ["วุ้นเส้น", "ผักสลัด", "น้ำยำไขมันต่ำ"],
        preparation: "ลวกวุ้นเส้นให้สุก ใส่น้ำยำไขมันต่ำและผักสลัด",
        precautions: "ควรเลือกน้ำยำที่ไม่มีน้ำตาลเพิ่ม",
        popularity: 4.4,
    },
    {
        name: "ผัดถั่วลันเตากุ้ง",
        image: "https://example.com/stir_fry_shrimp_snow_pea.jpg",
        benefits: "มีโปรตีนสูงและไฟเบอร์จากถั่วลันเตา",
        location: "333 ถนนพระราม 9, กรุงเทพฯ",
        calories: 220,
        category: "อาหารคาว",
        ingredients: ["ถั่วลันเตา", "กุ้ง", "กระเทียม", "น้ำมันมะกอก"],
        preparation: "ผัดถั่วลันเตาและกุ้งกับกระเทียมในน้ำมันมะกอก",
        precautions: "ควรใช้ปริมาณน้ำมันน้อย",
        popularity: 4.3,
    },
    {
        name: "ต้มจืดตำลึง",
        image: "https://example.com/spinach_soup.jpg",
        benefits: "มีวิตามินเอสูงและแคลอรี่ต่ำ",
        location: "444 ถนนรามคำแหง, กรุงเทพฯ",
        calories: 140,
        category: "อาหารคาว",
        ingredients: ["ตำลึง", "น้ำซุป", "กระเทียม"],
        preparation: "ต้มน้ำซุปให้เดือด ใส่ตำลึงและกระเทียม",
        precautions: "ควรระวังปริมาณเกลือในน้ำซุป",
        popularity: 4.2,
    },
];

export default savoryFoods;

